---
resources:
- name: source
  type: git
  source:
    uri: git@github.com:jobteaser/ci-connector.git
    branch: develop
    private_key: {{github-private-key}}

- name: docker-image
  type: docker-image
  source:
    username: {{docker-username}}
    password: {{docker-password}}
    repository: {{image}}

jobs:
- name: build-docker-image
  plan:
  - get: source
    trigger: true
  - put: docker-image
    params:
      build: source

